baseURL = "https://flamboyant-kilby-331d5c.netlify.com"
publishDir = "public"
languageCode = "en-us"
title = "Tyron Wytrykowski"
theme = "nederburg"
googleAnalytics = ""
# Enable comments by entering your Disqus shortname
disqusShortname = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  slogan = "Front-end Developer & Graphic Designer"
  description = "Tyron Wytrykowski Front-end web developer portfolio. South African born, and living in London. I have a passion for all things digital and creatively solving problems." # meta description
  copyright = [
    "&copy; 2018 Tyron Wytrykowski"
  ]


  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "resume/"
    weight = 2

  [[menu.main]]
    name = "Get in touch"
    url = "contact/"
    weight = 3

[params.social]
  email         = "email@example.com"
  twitter       = "https://twitter.com/TyronRGB"
  linkedin      = "https://www.linkedin.com/in/tyronwytrykowski/"
  github        = "https://github.com/tyronwyt"
  codepen       = "https://codepen.io/tyronw/"
